### ISSUE TITLE
On Device Type Casting

### ISSUE THREAD

**Issue by yodada** [cornell-brg/hb-pytorch#24]
## 🐛 Bug

Type casting on HammerBlade works for long -> int only.

## To Reproduce

This test demos the bug
```
def test_torch_to_int_to_long_1():
  x = torch.ones(10, dtype=torch.int)
  assert x.type() == 'torch.IntTensor'
  h = x.hammerblade()
  long_x = x.to(torch.long)
  ong_h = h.to(torch.long)
  assert long_h.type() == 'torch.hammerblade.LongTensor'
  assert long_h.device == torch.device("hammerblade")
  assert torch.equal(long_x, long_h.cpu())
```

**Comment by zzy82518996** [comment]
Hi Lin, is this because in the program it is ong_h instead of long_h?Sent from my Huawei phone-------- Original message --------From: Lin Cheng <notifications@github.com>Date: Thu, Mar 26, 2020, 6:34 PMTo: cornell-brg/hb-pytorch <hb-pytorch@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [cornell-brg/hb-pytorch] On Device Type Casting (#24)

🐛 Bug

Type casting on HammerBlade works for long -> int only.

To Reproduce

This test demos the bug

def test_torch_to_int_to_long_1():

  x = torch.ones(10, dtype=torch.int)

  assert x.type() == 'torch.IntTensor'

  h = x.hammerblade()

  long_x = x.to(torch.long)

  ong_h = h.to(torch.long)

  assert long_h.type() == 'torch.hammerblade.LongTensor'

  assert long_h.device == torch.device("hammerblade")

  assert torch.equal(long_x, long_h.cpu())

**Comment by yodada** [comment]
This is because the way I wrote `kernel_copy_hb_to_hb`.
The problem is related to this line https://github.com/cornell-brg/hb-pytorch/blob/efee78a4676d9fa8eea9e5d61b98c98b9e0b65d2/hammerblade/torch/kernel/kernel_copy_hb_to_hb.cpp#L21-L22
It assumes both the source and the destination are 32bits values. So 64bit integer -> 32bit integer copying is fine ... but others are not. I think at least ...

**Comment by yodada** [comment]
The correct way to do on device copying, is to do something like this
https://github.com/cornell-brg/hb-pytorch/blob/efee78a4676d9fa8eea9e5d61b98c98b9e0b65d2/aten/src/ATen/native/cpu/CopyKernel.cpp#L41-L63
We need to specialize for each pair of types
